### ISSUE TITLE
mojoconf.com: Admin > Purchases 'Captured' link

### ISSUE THREAD

**Issue by rpcme** [mojoconf/nyc-2015-06-05#24] opened 2015-04-20 22:42 UTC
The Captured link points to test dashboard, not live dashboard.  In such case, a 404 is returned.

Please change: 

test => ""

meaning:

https://dashboard.stripe.com/test/payments/(token)
->
https://dashboard.stripe.com/payments/(token)

**Comment by jhthorsen** [comment] 2015-04-21 19:25
This looks like a duplicate of https://github.com/mojoconf/MCT/issues/62

**Closed as completed by jhthorsen** 2015-04-21 19:25 UTC
